#!/usr/bin/env sh

# Bar configuration
yabai -m config external_bar all:0:0
yabai -m config window_border on
yabai -m config window_border_width 4
yabai -m config active_window_border_color 0xff89b4fa # Catppuccin Mocha Blue
yabai -m config normal_window_border_color 0xff313244 # Catppuccin Mocha Surface0
yabai -m config insert_feedback_color 0xffa6e3a1 # Catppuccin Mocha Green
yabai -m config window_placement second_child
yabai -m config window_shadow off

# Layout
yabai -m config layout bsp
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10

# Mouse
yabai -m config mouse_follows_focus on

# Rules
# Exclude System Settings and other floating windows
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^1Password$" manage=off

